[package]
name = "quickstart"
version = "0.1.3"
rust-version = "1.73"
authors = ["Denny Lee <denny.g.lee@gmail.com>"]
license = "Apache-2.0"
keywords = ["deltalake", "delta", "datalake", "deltars"]
description = "Quick Start Delta Lake Rust examples"
edition = "2021"

[dependencies]
datafusion = "49.0.0"
deltalake = { version = "1.4.0", features = ["datafusion"] }
tokio = { version = "1" }

[[example]]
name = "read_delta_table"

[[example]]
name = "read_delta_datafusion"